doctrine:
    orm:
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                is_bundle: false

stof_doctrine_extensions:
    orm:
        default:
            uploadable: false
            # loggable: true
         
    # uploadable:
        # default_file_path: "../upload/public"
        # mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        # default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo

services:
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ '%locale%' ] ]
            - [ setTranslationFallback, [ true ] ]
    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
    uca.listener.doctrineextension:
        class: App\Service\Listener\DoctrineExtensionListener
        calls:
            - [ setTranslatableListener, [ '@gedmo.listener.translatable' ] ]
            - [ setLoggableListener, [ '@gedmo.listener.loggable' ] ]
            - [ setTokenStorage, [ '@security.token_storage' ] ]
            - [ setAuthoriaztionChecker, [ '@security.authorization_checker' ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
