liip_imagine:
    # driver - one of the three drivers: gd, imagick, gmagick. Default value: gd
    driver: imagick
    default_image: null
    twig:
        mode: lazy
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public"
    resolvers :
        default :
            web_path : ~
    filter_sets :
        cache : ~

        header:
            filters:
                relative_resize:
                    heighten: 100
        
        home_carousel:
            filters:
                resize:
                    size: [300, 50]
        
        login_screen:
            filters:
                resize:
                    size: [300, 100]
                
        favicon:
            filters:
                resize:
                    size: [128, 128]
        
        mail_signature:
            filters:
                resize:
                    size: [250, 100]
        
        logo_pdf:
            filters:
                remove_alpha: ~
                resize:
                    size: [250, 100]
        
        footer:
            filters:
                relative_resize:
                    heighten: 60
        
        thumb_small:
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
    
        thumb_big:
            filters:
                thumbnail:
                    size: [64,64]
                    mode: outbound
        
        thumb_install_salle:
            filters:
                thumbnail:
                    size: [225,135]
                    mode: outbound

        thumb_partenaires_test-1:
            filters:
                thumbnail:
                    size: [200,200]
                    mode: inset

        thumb_logo_dt:
            filters:
                thumbnail:
                    size: [250,100]
                    mode: outbound

        thumb_large_small:
            filters:
                thumbnail:
                    size: [375,225]
                    mode: outbound
        thumb_large_big:
            filters:
                thumbnail:
                    size: [750,450]
                    mode: outbound
        thumb_background:
            filters:
                thumbnail:
                    size: [1920,1080]
                    mode: outbound
