security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Uca\Utilisateur
                property: email
        shibboleth_userbundle: 
            id: uca.shibboleth.provider

    password_hashers:
        App\Entity\Uca\Utilisateur: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        Shibboleth:
            pattern: /UcaWeb/ShibLogin 
            provider: shibboleth_userbundle
            logout: 
                path: UcaWeb_AppLogout
                target: UcaWeb_ShibLogout
            custom_authenticators: 
                - unicesil.shibboleth_authenticator
            # logout_on_user_change: true
            context: app
        main:
            provider: app_user_provider
            user_checker: App\Service\Securite\UserChecker
            form_login: true
            guard:
                authenticators:
                    - App\Service\Securite\LoginFormAuthenticator
            logout:
                path: UcaWeb_AppLogout
                target: UcaWeb_Accueil
            # logout_on_user_change: true
            entry_point: form_login
            context: app
    
    role_hierarchy: 
        # Basiques: 
        ROLE_ADMIN: ROLE_USER
        ACCESS_DENIED: ROLE_USER
        # Activité
        ROLE_GESTION_ACTIVITE_LECTURE: ROLE_ADMIN 
        ROLE_GESTION_ACTIVITE_ECRITURE: ROLE_GESTION_ACTIVITE_LECTURE 
        ROLE_GESTION_FORMAT_ACTIVITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_FORMAT_ACTIVITE_ECRITURE: ROLE_GESTION_FORMAT_ACTIVITE_LECTURE
        ROLE_GESTION_CLASSE_ACTIVITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_CLASSE_ACTIVITE_ECRITURE: ROLE_GESTION_CLASSE_ACTIVITE_LECTURE
        ROLE_GESTION_TYPE_ACTIVITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TYPE_ACTIVITE_ECRITURE: ROLE_GESTION_TYPE_ACTIVITE_LECTURE
        # Créneaux:
        ROLE_GESTION_CRENEAU_LECTURE: ROLE_ADMIN
        ROLE_GESTION_CRENEAU_ECRITURE: ROLE_GESTION_CRENEAU_LECTURE
        # Etablissements:
        ROLE_GESTION_ETABLISSEMENT_LECTURE: ROLE_ADMIN
        ROLE_GESTION_ETABLISSEMENT_ECRITURE: ROLE_GESTION_ETABLISSEMENT_LECTURE
        # Groupe
        ROLE_GESTION_GROUPE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_GROUPE_ECRITURE: ROLE_GESTION_GROUPE_LECTURE
        # Logs
        ROLE_GESTION_LOG_LECTURE: ROLE_ADMIN
        # Profils
        ROLE_GESTION_PROFIL_UTILISATEUR_LECTURE: ROLE_ADMIN
        ROLE_GESTION_PROFIL_UTILISATEUR_ECRITURE: ROLE_GESTION_PROFIL_UTILISATEUR_LECTURE
        # REssources
        ROLE_GESTION_RESSOURCE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_RESSOURCE_ECRITURE: ROLE_GESTION_RESSOURCE_LECTURE
        # Tarif:
        ROLE_GESTION_TARIF_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TARIF_ECRITURE:  ROLE_GESTION_TARIF_LECTURE
        # Texte
        ROLE_GESTION_TEXTE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TEXTE_ECRITURE: ROLE_GESTION_TEXTE_LECTURE
        # Image de fond
        ROLE_GESTION_IMAGEFOND_LECTURE: ROLE_ADMIN
        ROLE_GESTION_IMAGEFOND_ECRITURE: ROLE_GESTION_IMAGEFOND_LECTURE
        # Logo partenaire
        ROLE_GESTION_LOGOPARTENAIRE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_LOGOPARTENAIRE_ECRITURE: ROLE_GESTION_LOGOPARTENAIRE_LECTURE
        # Niveau Sportif
        ROLE_GESTION_NIVEAUSPORTIF_LECTURE: ROLE_ADMIN
        ROLE_GESTION_NIVEAUSPORTIF_ECRITURE: ROLE_GESTION_NIVEAUSPORTIF_LECTURE
        # Trauction
        ROLE_GESTION_TRADUCTION_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TRADUCTION_ECRITURE: ROLE_GESTION_TRADUCTION_LECTURE
        # Type Autorisation
        ROLE_GESTION_TYPE_AUTORISATION_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TYPE_AUTORISATION_ECRITURE: ROLE_GESTION_TYPE_AUTORISATION_LECTURE
        # Utilisateur
        ROLE_GESTION_UTILISATEUR_LECTURE: ROLE_ADMIN
        ROLE_GESTION_UTILISATEUR_ECRITURE:  ROLE_GESTION_UTILISATEUR_LECTURE
        # Actualite
        ROLE_GESTION_ACTUALITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_ACTUALITE_ECRITURE:  ROLE_GESTION_ACTUALITE_LECTURE
        # Highlights
        ROLE_GESTION_HIGHLIGHT_LECTURE: ROLE_ADMIN
        ROLE_GESTION_HIGHLIGHT_ECRITURE: ROLE_GESTION_HIGHLIGHT_LECTURE
        # Shnu_Highlights
        ROLE_GESTION_SHNU_HIGHLIGHT_LECTURE: ROLE_ADMIN
        ROLE_GESTION_SHNU_HIGHLIGHT_ECRITURE: ROLE_GESTION_SHNU_HIGHLIGHT_LECTURE
        # Gestion des rubriques SHNU
        ROLE_GESTION_SHNU_RUBRIQUE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_SHNU_RUBRIQUE_ECRITURE: ROLE_GESTION_SHNU_RUBRIQUE_LECTURE
        
        # Gestionnaire de Panier
        ROLE_GESTION_PAIEMENT_COMMANDE: ROLE_ADMIN
        # Inscription a valider
        ROLE_ENCADRANT: ROLE_ADMIN
        ROLE_GESTIONNAIRE_VALIDEUR_INSCRIPTION: ROLE_ADMIN
        # Scheduler
        ROLE_GESTION_SCHEDULER_LECTURE: ROLE_ADMIN
        # Gestion de toutes les commandes
        ROLE_GESTION_COMMANDES: ROLE_ADMIN
        # Gestion de toutes les inscriptions
        ROLE_GESTION_INSCRIPTION: ROLE_ADMIN
        # Gestion du paramétrage
        ROLE_GESTION_PARAMETRAGE: ROLE_ADMIN
        #Previsualisation
        ROLE_PREVISUALISATION: ROLE_ADMIN
        # Emailing
        ROLE_GESTION_EMAILING: ROLE_ADMIN
        #Bascule
        ROLE_GESTION_BASCULE: ROLE_ADMIN
        # Gestion des extractions
        ROLE_GESTION_EXTRACTION: ROLE_ADMIN
        #Suppression de masse
        ROLE_GESTION_SUPPRESSION_MASSIVE: ROLE_ADMIN
        # Gestion des avoirs
        ROLE_GESTION_AVOIR: ROLE_ADMIN
        ROLE_GESTION_CREDIT_UTILISATEUR_LECTURE: ROLE_ADMIN
        ROLE_GESTION_CREDIT_UTILISATEUR_ECRITURE: ROLE_GESTION_CREDIT_UTILISATEUR_LECTURE
        
        # Tous les groupes:
        ROLE_SUPER_ADMIN : [
            ROLE_ENCADRANT,
            ROLE_GESTIONNAIRE_VALIDEUR_INSCRIPTION,
            ROLE_GESTION_ACTIVITE_ECRITURE,
            ROLE_GESTION_ACTUALITE_ECRITURE,
            ROLE_GESTION_AVOIR,
            ROLE_GESTION_BASCULE,
            ROLE_GESTION_CLASSE_ACTIVITE_ECRITURE,
            ROLE_GESTION_COMMANDES,
            ROLE_GESTION_CREDIT_UTILISATEUR_ECRITURE,
            ROLE_GESTION_CRENEAU_ECRITURE,
            ROLE_GESTION_ETABLISSEMENT_ECRITURE,
            ROLE_GESTION_EXTRACTION,
            ROLE_GESTION_EMAILING,
            ROLE_GESTION_FORMAT_ACTIVITE_ECRITURE,
            ROLE_GESTION_GROUPE_ECRITURE,
            ROLE_GESTION_HIGHLIGHT_ECRITURE,
            ROLE_GESTION_IMAGEFOND_ECRITURE,
            ROLE_GESTION_INSCRIPTION,
            ROLE_GESTION_NIVEAUSPORTIF_ECRITURE,
            ROLE_GESTION_LOGOPARTENAIRE_ECRITURE,
            ROLE_GESTION_LOG_LECTURE,
            ROLE_GESTION_PAIEMENT_COMMANDE,
            ROLE_GESTION_PARAMETRAGE,
            ROLE_GESTION_PROFIL_UTILISATEUR_ECRITURE,
            ROLE_GESTION_RESSOURCE_ECRITURE,
            ROLE_GESTION_SCHEDULER_LECTURE,
            ROLE_GESTION_SHNU_HIGHLIGHT_ECRITURE,
            ROLE_GESTION_SHNU_RUBRIQUE_LECTURE,
            ROLE_GESTION_SHNU_RUBRIQUE_ECRITURE,
            ROLE_GESTION_SUPPRESSION_MASSIVE,
            ROLE_GESTION_TARIF_ECRITURE,
            ROLE_GESTION_TEXTE_ECRITURE,
            ROLE_GESTION_TRADUCTION_ECRITURE,
            ROLE_GESTION_TYPE_ACTIVITE_ECRITURE,
            ROLE_GESTION_TYPE_AUTORISATION_ECRITURE,
            ROLE_GESTION_UTILISATEUR_ECRITURE,
            ROLE_PREVISUALISATION]

    access_control:
        - path: /UcaGest/Groupe/Modifier | /UcaGest/Groupe/Ajouter
          role: ROLE_GESTION_GROUPE_ECRITURE
        - path: /UcaGest/Utilisateur/Enregistrement
          role: ROLE_GESTION_UTILISATEUR_ECRITURE
        - path: /UcaWeb/ShibLogin
          role: IS_AUTHENTICATED_FULLY 
        - path: / | /UcaGest/Connexion | /UcaWeb/Reinitialiser/Envoyer
          role: IS_AUTHENTICATED_ANONYMOUSLY
