CREATE TABLE format_activite_lieu (format_activite_id INT NOT NULL, lieu_id INT NOT NULL, INDEX IDX_1C630F7B8C5FABB (format_activite_id), INDEX IDX_1C630F7B6AB213CC (lieu_id), PRIMARY KEY(format_activite_id, lieu_id)) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_unicode_ci ENGINE = InnoDB;
CREATE TABLE actualite (id INT AUTO_INCREMENT NOT NULL, ordre INT DEFAULT NULL, titre VARCHAR(255) NOT NULL, texte LONGTEXT NOT NULL, image VARCHAR(255) NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_unicode_ci ENGINE = InnoDB;
ALTER TABLE format_activite_lieu ADD CONSTRAINT FK_1C630F7B8C5FABB FOREIGN KEY (format_activite_id) REFERENCES format_activite (id) ON DELETE CASCADE;
ALTER TABLE format_activite_lieu ADD CONSTRAINT FK_1C630F7B6AB213CC FOREIGN KEY (lieu_id) REFERENCES ressource (id) ON DELETE CASCADE;
ALTER TABLE format_activite DROP FOREIGN KEY FK_1F4F65C16AB213CC;
DROP INDEX IDX_1F4F65C16AB213CC ON format_activite;
ALTER TABLE format_activite DROP lieu_id;
ALTER TABLE utilisateur ADD shibboleth TINYINT(1) DEFAULT '0' NOT NULL;