# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
                default:
                    driver: pdo_mysql
                    host: '%database_host%'
                    port: '%database_port%'
                    dbname: '%database_name%'
                    user: '%database_user%'
                    password: '%database_password%'
                    charset: UTF8
                statistique:
                    driver: pdo_mysql
                    host: '%database_host%'
                    port: '%database_port%'
                    dbname: '%database_statistiques_name%'
                    user: '%database_user%'
                    password: '%database_password%'
                    charset: UTF8
        

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'                
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    UcaBundle:  ~
                dql:
                    string_functions:
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
            statistique:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: statistique
                mappings:
                    StatistiqueBundle: ~
                dql:
                    string_functions:
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
