lexik_paybox:
    parameters:
        production:  true        # Switches between Paybox test and production servers (preprod-tpe <> tpe)
        site:        '2395917'   # Site number provided by the bank
        rank:        '01'        # Rank number provided by the bank
        login:       '239591701' # Customer's login provided by Paybox
        hmac:
            key: '649E8E791D3455CD78BCF5CF6DC74CF60ABFFE3887886BBD23DB847540447CD6924EBCFEAC10894FDB2B14E1AACDB78DC18772C39E6429965FEBF71456C54875' # Key used to compute the hmac hash, provided by Paybox
        currencies:  
            - '978'  # EUR