# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    auth_mode: '%mailer_auth_mode%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
