# Swiftmailer Configuration
swiftmailer:
    # transport: gmail
    # username:  '%mailer_user%'
    # password:  Atimic2019
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
