framework:
    templating:
        engines: ['twig']
        
twig:
    globals:
        twig_tools: "@uca.tools"
        lang_all: '%lang.all%'
        fos_csrf_provider: "@security.csrf.token_manager"
        sitemap: "@uca.sitemap"
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig', '@FOSCKEditor/Form/ckeditor_widget.html.twig']