parameters:
    lang.all: fr|en
    lang.default: fr

services:
    # SERVICES - GENERAL
    uca.tools:
        class: UcaBundle\Service\Common\Tools
    uca.sitemap:
        class: UcaBundle\Service\Common\SiteMap
        arguments: ['%kernel.root_dir%', '@request_stack', '@router', '@translator', '@security.authorization_checker']
    uca.translatable:
        class: UcaBundle\Service\Common\Translatable
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']
    uca.annotation.tools:
        class: UcaBundle\Service\Common\Annotation
        arguments: ['@doctrine.orm.entity_manager']
    uca.flashbag:
        class: UcaBundle\Service\Common\FlashBag
        arguments: ['@translator', '@request_stack']
    uca.shibboleth.provider:
        class: UcaBundle\Service\Securite\GestionnaireUtilisateurShibboleth
        arguments: ['@doctrine.orm.entity_manager','@fos_user.user_manager']
   
    # SERVICES - FONCTIONNALITES
    uca.paybox:
        class: UcaBundle\Service\Securite\PayBox
        arguments: ['@lexik_paybox.request_handler', '@router', '@templating']
    uca.inscription:
        class: UcaBundle\Service\Service\InscriptionService
        autowire: true
        public: true
    uca.timeout:
        class: UcaBundle\Service\Securite\TimeoutService
        autowire: true
        public: true
    uca.creationPdf: 
        class: UcaBundle\Service\Common\CreationPdf
        arguments: ['@doctrine.orm.entity_manager','@templating']
    uca.extraction.excel: 
        class: UcaBundle\Service\Service\ExtractionExcelService
        arguments: ['@translator']
    mailService:
        class: UcaBundle\Service\Common\MailService
        arguments: ['@mailer', '%mailer_sender%', '@templating', '@uca.flashbag']
    UcaBundle\Service\Common\MailService: '@mailService'
    uca.calendrier:
        class: UcaBundle\Service\Service\CalendrierService
        arguments: ['@doctrine.orm.entity_manager', '@templating', '@translator']

    # SERVICES - LISTENERS
    # Entity Listeners
    uca.doctrine.commande.listener:
        class: UcaBundle\Service\Listener\Entity\CommandeListener
        autowire: true
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: App\Entity\Commande }
    uca.doctrine.groupe.listener:
        class: UcaBundle\Service\Listener\Entity\GroupeListener
        arguments: ['@translator']
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: App\Entity\Groupe, method: postPersist }
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\Groupe, method: preFlush }
    uca.doctrine.inscription.listener:
        class: UcaBundle\Service\Listener\Entity\InscriptionListener
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: App\Entity\Inscription, method: prePersist }
    uca.doctrine.classe_activite.listener:
        class: UcaBundle\Service\Listener\Entity\ClasseActiviteListener
        tags:
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\ClasseActivite, method: preFlush }
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest }
    uca.doctrine.activite.listener:
        class: UcaBundle\Service\Listener\Entity\ActiviteListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest }
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\Activite, method: preFlush }
    uca.doctrine.format_activite.listener:
        class: UcaBundle\Service\Listener\Entity\FormatActiviteListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest }
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\FormatActivite, method: preFlush }
    uca.doctrine.creneau.listener:
        class: UcaBundle\Service\Listener\Entity\CreneauListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest }
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\Creneau, method: preFlush }
    uca.doctrine.format_achat_carte.listener:
        class: UcaBundle\Service\Listener\Entity\FormatAchatCarteListener
        tags:
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\FormatAchatCarte, method: preFlush }
    uca.doctrine.format_avec_reservation.listener:
        class: UcaBundle\Service\Listener\Entity\FormatAvecReservationListener
        tags:
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\FormatAvecReservation, method: preFlush }
    uca.doctrine.type_autorisation.listener:
        class: UcaBundle\Service\Listener\Entity\TypeAutorisationListener
        tags:
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\TypeAutorisation, method: preFlush }
    uca.doctrine.ressource.listener:
        class: UcaBundle\Service\Listener\Entity\RessourceListener
        tags:
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\Ressource, method: preFlush }
    uca.doctrine.logopartenaire.listener:
        class: UcaBundle\Service\Listener\Entity\LogoPartenaireListener
        tags:
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: App\Entity\LogoPartenaire, method: preFlush }
    
    # Other Listerners
    uca.paybox_response_listener:
        class: UcaBundle\Service\Listener\PayboxResponseListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: paybox.ipn_response, method: onPayboxIpnResponse }
    uca.previsualisation:
        class: UcaBundle\Service\Common\Previsualisation
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: ['@security.token_storage', '@security.authorization_checker']
    uca.historique_navigation:
        class: UcaBundle\Service\Common\HistoriqueNavigation
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    uca.parametrage:
        class: UcaBundle\Service\Common\Parametrage
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    uca.user.registration.listener:
        class: UcaBundle\Service\Listener\RegistrationConfirmListener
        autowire: true
        tags:
            - { name: kernel.event_subscriber }
        arguments: ['@doctrine.orm.entity_manager', '@router', '@uca.flashbag']
    uca.listener.exception:
        class: UcaBundle\Service\Listener\ExceptionListener
        arguments: ['@router', '@uca.flashbag', '@mailService', '%mailer_exception%', '@doctrine.orm.entity_manager', '@doctrine.dbal.default_connection']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    uca.selection.profil: 
        class: UcaBundle\Service\Service\SelectionProfil
        arguments: ['%kernel.root_dir%','@router', '@translator']
    UcaBundle\Service\Service\SelectionProfil: '@uca.selection.profil'
    uca.form.profilUtilisateur:
        class: UcaBundle\Form\FormatActiviteProfilUtilisateurType
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]
    uca.form.ressourceprofilUtilisateur:
        class: UcaBundle\Form\RessourceProfilUtilisateurType
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]
    UcaBundle\Service\Listener\Securite\Utilisateur\LoginListener:
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    uca.extraction.inscription:
        class: UcaBundle\Service\Service\ExtractionInscriptionService
        arguments: ['@doctrine.orm.entity_manager']
    uca.form.gestioninscription:
        class: UcaBundle\Form\GestionInscriptionType
        arguments: ['@uca.extraction.inscription']
        tags: [form.type]
      
