unice_sil_shibboleth:
    # The path used to call Shibboleth login authentication (default = 'Shibboleth.sso/Login')
    login_path: 'Shibboleth.sso/Login'  
    # The path used to call Shibboleth logout (default = 'Shibboleth.sso/Logout')  
    logout_path: 'Shibboleth.sso/Logout' 
    # The Shibboleth attribute that is used as username for the logged in user. 
    # The attribute must appear in the'attributes' parameter list (default = 'username')
    username: 'eppn'  
    # The list of attributes returned by Shibboleth Service Provider
    # Champs Shibbolteh
    # 'Application ID' : en tete HTTP poru récupérer application
    # 'eduPersonPrincipalName' : identifiant unique personnel
    # 'upannEmpId' : identifiaant d'un employé
    # 'uid' :identifiant unique oru l'étudiant
    # 'cn' : nom complet sans accent
    # 'displayName' : nom complet avec accent 
    # 'eduPersonNickname' : nom d'affichage / pseudo
    # 'givenName' : prénom
    # 'L' (localiy) : ville
    # 'mail' : adresse email de l'université
    # 'mifare' : identifiant unique carte étudiant
    # 'mobile' : numéro de portable
    # 'telephoneNumer' : numéro de téléphpone
    # 'postalAddress' : adresse
    # 'userCertificate' : certificat X509 
    # 'userPassword' : mot de passe
    # 'eduPersonPrimaryAffiliation' : affiliation primaire (enseignant ou élève)
    #''eduPersonScopedAffiliation' : tableau des affiliations
    # 'supannCivilite' : civilité 
    # 'supannMailPerso' : email personnel
    
    attributes: [
        'uid',
        'eppn',
        'mail', 
        'givenName',
        'sn',
        'eduPersonAffiliation',
        'eduPersonPrimaryAffiliation',
        'supannEtuId', 
        'ptdrouv',
        'mifare'] 
    # The route to which the user will be redirected after login. If this parameter is not filled, the user will be redirected to the page from which he comes. (default = null)
    # Probablement UcaWeb_acceuil
    login_target: null  
    # The route to which the user will be redirected after logout. If this parameter is not filled, the user will be redirected to the page from which he comes. (default = null)
    # Probablement UcaWeb_acceuil
    logout_target: null  

