vich_uploader:
    db_driver: orm
    mappings: 
        map_image:
            uri_prefix:         /upload/public/image
            upload_destination: '%kernel.project_dir%/web/upload/public/image' 
            namer: vich_uploader.namer_uniqid
            # inject_on_load: false
            delete_on_update: true
            delete_on_remove: true  

        referentiel_immobilier:
            uri_prefix:    /upload/public/fichiers
            upload_destination: '%kernel.project_dir%/web/upload/public/fichiers'
            delete_on_update: true
            delete_on_remove: true