vich_uploader:
    db_driver: orm
    mappings: 
        map_image:
            uri_prefix:         /upload/public/image
            upload_destination: '%kernel.project_dir%/web/upload/public/image' 
            namer: vich_uploader.namer_uniqid
            # inject_on_load: false
            delete_on_update: true
            delete_on_remove: true  
        
        utilisateur_document:
            uri_prefix:     /upload/public/documents
            upload_destination: '%kernel.project_dir%/web/upload/public/documents'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true

        referentiel_immobilier:
            uri_prefix:    /upload/public/fichiers
            upload_destination: '%kernel.project_dir%/web/upload/public/fichiers'
            delete_on_update: true
            delete_on_remove: true

        justificatif:
            uri_prefix:    /upload/private/fichiers
            upload_destination: '%kernel.project_dir%/web/upload/private/fichiers'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true
        
 
        