parameters:
    onurb_yuml.direction: TB
    onurb_yuml.colors:
        FOS\UserBundle\Model\Group: gold
        FOS\UserBundle\Model\User: gold
        UcaBundle\Entity\Activite: red
        UcaBundle\Entity\FormatAvecCreneau: red
        UcaBundle\Entity\FormatAvecReservation: red
        UcaBundle\Entity\FormatSimple: red
        UcaBundle\Entity\Article: orange
        UcaBundle\Entity\Autorisation: mediumseagreen
        UcaBundle\Entity\ClasseActivite: orangered
        UcaBundle\Entity\Commande: orange
        UcaBundle\Entity\ComportementAutorisation: mediumseagreen
        UcaBundle\Entity\Creneau: palevioletred
        UcaBundle\Entity\Etablissement: royalblue
        UcaBundle\Entity\DhtmlxDate: green
        UcaBundle\Entity\DhtmlxEvenement: green
        UcaBundle\Entity\DhtmlxSerie: green
        UcaBundle\Entity\Groupe: gold
        UcaBundle\Entity\Inscription: palevioletred
        UcaBundle\Entity\IntervalleDate: darkviolet
        UcaBundle\Entity\Lieu: royalblue
        UcaBundle\Entity\Materiel: royalblue
        UcaBundle\Entity\Panier: orange
        UcaBundle\Entity\ProfilUtilisateur: gold
        UcaBundle\Entity\Reservabilite: palevioletred
        UcaBundle\Entity\Reservation: palevioletred
        UcaBundle\Entity\Ressource: royalblue
        UcaBundle\Entity\Tarif: orange
        UcaBundle\Entity\TypeActivite: orangered
        UcaBundle\Entity\TypeAutorisation: mediumseagreen
        UcaBundle\Entity\Utilisateur: gold
