security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        shibboleth_userbundle: 
            id: uca.shibboleth.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        Shibboleth:
            pattern: /UcaWeb/ShibLogin 
            provider: shibboleth_userbundle
            anonymous: true
            logout: 
                path: UcaWeb_AppLogout
                target: UcaWeb_ShibLogout
            guard:
              authenticators:
                - unicesil.shibboleth_authenticator
            logout_on_user_change: true
            context: app
        FoSUser:
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: UcaWeb_AppLogout
                target: /
            logout_on_user_change: true
            anonymous: true
            context: app

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    
    role_hierarchy: 
        # Basiques: 
        ROLE_ADMIN: ROLE_USER
        # Activité
        ROLE_GESTION_ACTIVITE_LECTURE: ROLE_ADMIN 
        ROLE_GESTION_ACTIVITE_ECRITURE: ROLE_GESTION_ACTIVITE_LECTURE 
        ROLE_GESTION_FORMAT_ACTIVITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_FORMAT_ACTIVITE_ECRITURE: ROLE_GESTION_FORMAT_ACTIVITE_LECTURE
        ROLE_GESTION_CLASSE_ACTIVITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_CLASSE_ACTIVITE_ECRITURE: ROLE_GESTION_CLASSE_ACTIVITE_LECTURE
        ROLE_GESTION_TYPE_ACTIVITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TYPE_ACTIVITE_ECRITURE: ROLE_GESTION_TYPE_ACTIVITE_LECTURE
        # Créneaux:
        ROLE_GESTION_CRENEAU_LECTURE: ROLE_ADMIN
        ROLE_GESTION_CRENEAU_ECRITURE: ROLE_GESTION_CRENEAU_LECTURE
        # Etablissements:
        ROLE_GESTION_ETABLISSEMENT_LECTURE: ROLE_ADMIN
        ROLE_GESTION_ETABLISSEMENT_ECRITURE: ROLE_GESTION_ETABLISSEMENT_LECTURE
        # Groupe
        ROLE_GESTION_GROUPE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_GROUPE_ECRITURE: ROLE_GESTION_GROUPE_LECTURE
        # Logs
        ROLE_GESTION_LOG_LECTURE: ROLE_ADMIN
        # Profils
        ROLE_GESTION_PROFIL_UTILISATEUR_LECTURE: ROLE_ADMIN
        ROLE_GESTION_PROFIL_UTILISATEUR_ECRITURE: ROLE_GESTION_PROFIL_UTILISATEUR_LECTURE
        # REssources
        ROLE_GESTION_RESSOURCE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_RESSOURCE_ECRITURE: ROLE_GESTION_RESSOURCE_LECTURE
        # Tarif:
        ROLE_GESTION_TARIF_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TARIF_ECRITURE:  ROLE_GESTION_TARIF_LECTURE
        # Texte
        ROLE_GESTION_TEXTE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TEXTE_ECRITURE: ROLE_GESTION_TEXTE_LECTURE
        # Image de fond
        ROLE_GESTION_IMAGEFOND_LECTURE: ROLE_ADMIN
        ROLE_GESTION_IMAGEFOND_ECRITURE: ROLE_GESTION_IMAGEFOND_LECTURE
        # Trauction
        ROLE_GESTION_TRADUCTION_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TRADUCTION_ECRITURE: ROLE_GESTION_TRADUCTION_LECTURE
        # Type Autorisation
        ROLE_GESTION_TYPE_AUTORISATION_LECTURE: ROLE_ADMIN
        ROLE_GESTION_TYPE_AUTORISATION_ECRITURE: ROLE_GESTION_TYPE_AUTORISATION_LECTURE
        # Utilisateur
        ROLE_GESTION_UTILISATEUR_LECTURE: ROLE_ADMIN
        ROLE_GESTION_UTILISATEUR_ECRITURE:  ROLE_GESTION_UTILISATEUR_LECTURE
        # Actualite
        ROLE_GESTION_ACTUALITE_LECTURE: ROLE_ADMIN
        ROLE_GESTION_ACTUALITE_ECRITURE:  ROLE_GESTION_ACTUALITE_LECTURE
        
        # Gestionnaire de Panier
        ROLE_GESTION_PAIEMENT_COMMANDE: ROLE_ADMIN

        # Inscription a valider
        ROLE_ENCADRANT: ROLE_ADMIN
        ROLE_GESTIONNAIRE_VALIDEUR_INSCRIPTION: ROLE_ADMIN
        
        # Scheduler
        ROLE_GESTION_SCHEDULER_LECTURE: ROLE_ADMIN

        # Gestion de toutes les commandes
        ROLE_GESTION_COMMANDES: ROLE_ADMIN

        # Gestion de toutes les inscriptions
        ROLE_GESTION_INSCRIPTION: ROLE_ADMIN

        # Gestion du paramétrage
        ROLE_GESTION_PARAMETRAGE: ROLE_ADMIN
        
        #Previsualisation
        ROLE_PREVISUALISATION: ROLE_ADMIN
        
        # Tous les groupes:
        ROLE_SUPER_ADMIN : [
            ROLE_ENCADRANT,
            ROLE_GESTIONNAIRE_VALIDEUR_INSCRIPTION,
            ROLE_GESTION_ACTIVITE_ECRITURE,
            ROLE_GESTION_ACTUALITE_ECRITURE,
            ROLE_GESTION_CLASSE_ACTIVITE_ECRITURE,
            ROLE_GESTION_CRENEAU_ECRITURE,
            ROLE_GESTION_ETABLISSEMENT_ECRITURE,
            ROLE_GESTION_FORMAT_ACTIVITE_ECRITURE,
            ROLE_GESTION_GROUPE_ECRITURE,
            ROLE_GESTION_IMAGEFOND_ECRITURE,
            ROLE_GESTION_LOG_LECTURE,
            ROLE_GESTION_PAIEMENT_COMMANDE,
            ROLE_GESTION_PROFIL_UTILISATEUR_ECRITURE,
            ROLE_GESTION_RESSOURCE_ECRITURE,
            ROLE_GESTION_SCHEDULER_LECTURE,
            ROLE_GESTION_TARIF_ECRITURE,
            ROLE_GESTION_TEXTE_ECRITURE,
            ROLE_GESTION_TRADUCTION_ECRITURE,
            ROLE_GESTION_TYPE_ACTIVITE_ECRITURE,
            ROLE_GESTION_TYPE_AUTORISATION_ECRITURE,
            ROLE_GESTION_UTILISATEUR_ECRITURE,
            ROLE_GESTION_COMMANDES,
            ROLE_GESTION_PARAMETRAGE,
            ROLE_PREVISUALISATION,
            ROLE_GESTION_INSCRIPTION]

        #ACCES_HISTORIQUE_COMMANDE: ROLE_USER
        #ACCES_PLANNING: ROLE_USER
        #GESTION_EQUIPEMENT_RESERVABLE: ROLE_USER
        #GESTION_FEUILLE_PRESENCE: ROLE_USER
        #VALIDER_AUTORISATION_SPORTIVE: ROLE_USER
        
    access_control:
        - path: /UcaGest/Groupe/Modifier | /UcaGest/Groupe/Ajouter
          role: ROLE_GESTION_GROUPE_ECRITURE
        - path: /UcaGest/Utilisateur/Enregistrement
          role: ROLE_GESTION_UTILISATEUR_ECRITURE
        - path: /UcaWeb/ShibLogin
          role: IS_AUTHENTICATED_FULLY 
        - path: / | /UcaGest/Connexion | /UcaWeb/Reinitialiser/Envoyer
          role: IS_AUTHENTICATED_ANONYMOUSLY
