imports:
    - { resource: symfony/parameters.yml }
    - { resource: symfony/security.yml }
    - { resource: symfony/services.yml }
    - { resource: symfony/lang.yml }
    - { resource: bundles/doctrine.yml }
    - { resource: bundles/fos.yml }
    - { resource: bundles/gedmo.yml }
    - { resource: bundles/liip.yml }
    - { resource: bundles/sg_datatables.yml }
    - { resource: bundles/swiftmailer.yml }
    - { resource: bundles/twig.yml }
    - { resource: bundles/uca.yml }
    - { resource: bundles/vichUploader.yml }
    - { resource: bundles/webpack.yml }
    - { resource: bundles/yuml.yml }
    - { resource: bundles/ckeditor.yml }
    - { resource: bundles/uniceShibboleth.yml }
    - { resource: bundles/bazinga_js_translation.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/routing/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: { enabled: true }
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        base_path: '/build'
    php_errors:
        log: true

sensio_framework_extra:
   router:
        annotations: false
