<?php

namespace UcaBundle\Repository;

/**
 * ActiviteAvecCreneauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteAvecCreneauRepository extends ActiviteRepository
{
}
