<?php

namespace UcaBundle\Repository;

/**
 * AutorisationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorisationRepository extends FormatActiviteRepository
{
    public function findFinishedAutorisations()
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.inscription', 'i')
            ->leftJoin('i.formatActivite', 'fa')
            ->where('fa.dateFinEffective <= :now')
            ->setParameter('now', new \DateTime())
        ;

        return $qb->getQuery()->getResult();
    }
}
