<?php

namespace UcaBundle\Repository;

use UcaBundle\Entity\FormatAvecCreneau;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DhtmlxEvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDhtmlxDateByReference($type, $id)
    {
        if ($type == "ressource") {
            return $this->createQueryBuilder("e")
                ->leftJoin("e.reservabilite", "re")
                ->leftJoin("re.ressource", "r")
                ->where("r.id = :id")
                ->andWhere("e.serie is null")
                ->setParameter("id", $id)
                ->getQuery()
                ->getResult(); 
        }
        elseif ($type == "FormatActivite") {
            /* tous les évenements pour le type FormatActivite font partie d'une serie */
        }
    }
    
    public function findDhtmlxReservabiliteByUser($user){
        return  $this->createQueryBuilder("d")
        ->join("d.reservabilite", "r")
        ->join("r.inscriptions", "i")
        ->where("i.utilisateur = :user")
        ->setParameter("user", $user)
        ->andWhere("i.statut = :statut")
        ->setParameter("statut", 'valide')
        ->getQuery()
        ->getResult();
    }
    
    public function findDhtmlxFormatSimpleByUser($user){
        return  $this->createQueryBuilder("d")
        ->join("d.formatSimple", "fs")
        ->join("fs.inscriptions", "i")
        ->where("i.utilisateur = :user")
        ->setParameter("user", $user)
        ->andWhere("i.statut = :statut")
        ->setParameter("statut", 'valide')
        ->getQuery()
        ->getResult();
    }
    
    public function findDhtmlxFormatSimpleByEncadrant($user){
        return  $this->createQueryBuilder("d")
        ->join("d.formatSimple", "fs")
        ->join("fs.encadrants", "e")
        ->andWhere("e.id = :userid")
        ->setParameter("userid", $user->getId())
        ->getQuery()
        ->getResult();
    }
}
