<?php

namespace UcaBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatSimpleRepository extends \Doctrine\ORM\EntityRepository
{

    public function PromotionsPagination($page, $nbMaxParPage){
        $qb = $this->createQueryBuilder('a')
        ->orderBy('a.dateDebutEffective', 'DESC');   
        
        $query = $qb->getQuery();

        $premierResultat = ($page - 1) * $nbMaxParPage;
        $query->setFirstResult($premierResultat)->setMaxResults($nbMaxParPage);
        $paginator = new Paginator($query);

        return $paginator;
    }
}

