<?php

namespace UcaBundle\Repository;

use UcaBundle\Service\Common\Previsualisation;

/**
 * ActiviteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    public function enCoursPublication($qb, $alias = 'f')
    {
        $qb->andWhere($alias.'.statut = 1')
            ->andWhere($alias.'.dateDebutPublication <= :today')
            ->andWhere($alias.'.dateFinPublication >= :today')
            ->setParameter('today', new \Datetime('now'))
        ;
    }

    public function findFormatPublie($activite = null, $user)
    {
        $qb = $this
            ->createQueryBuilder('f')
        ;

        if (null !== $user) {
            $qb
                ->leftJoin('f.profilsUtilisateurs', 'fp')
                ->leftJoin('fp.profilUtilisateur', 'p')
                ->leftJoin('p.utilisateur', 'u')
                ->andWhere('u.id = :idUtilisateur')
                ->setParameter('idUtilisateur', $user->getId())
            ;
        }

        if (!Previsualisation::$IS_ACTIVE) {
            $this->enCoursPublication($qb);
        }

        if (!empty($activite)) {
            $qb->andWhere('f.activite = :activite')
                ->setParameter('activite', $activite)
            ;
        }

        return $qb->getQuery()
            ->getResult()
        ;
    }
}
