<?php

namespace UcaBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFormatPublie($activite)
    {
        return $this
            ->createQueryBuilder('f')
            ->where('f.activite = :activite')
            ->andWhere('f.statut = 1')
            ->andWhere('f.dateDebutPublication <= :today')
            ->andWhere('f.dateFinPublication >= :today')
            ->setParameter('activite', $activite)
            ->setParameter('today', new \Datetime('now'))
            ->getQuery()
            ->getResult();
    }

}
