<?php

namespace UcaBundle\Repository;

/**
 * FormatAchatCarteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatAchatCarteRepository extends FormatActiviteRepository
{
    public function findFinishedFormats()
    {
        $qb = $this->createQueryBuilder('f')
            ->where('f.dateFinEffective <= :now')
            ->setParameter('now', new \DateTime())
        ;

        return $qb->getQuery()->getResult();
    }
}
