# sitemap.yml
# arborescence de pages qui sert à générer le fil d'ariane en fonction de la page sur laquelle on se trouve
# chaque page contient les élements suivants :
# - titre : libelle qui sera affiché (si on spécifie un tableau, le Service SiteMap generera le libelle en fonction de l'item courant de la page en fonction de la classe de l'item)
# - route : permet au Service SiteMap d'identifier sur quelle page on se trouve et de générer les urls du fil d'ariane
# - items : liste des routes faisant partie de la route courante.

      
# Branche Uca Web
- titre: "trans('sitemap.ucasport.libelle')"
  menuLevel: 1
  route: UcaWeb_Accueil
  items:
    - titre: "trans('sitemap.activites.libelle')"
      route: UcaWeb_ClasseActiviteLister
      items:
        - titre: "item.getClasseActiviteLibelle()"
          route: UcaWeb_ActiviteLister
          params: { id: idCa }
          items:
            - titre: "item.getActiviteLibelle()"
              route: UcaWeb_FormatActiviteLister
              params: { idCa: idCa, id: idA }
              items:
                - titre: "item.getLibelle()"
                  route: UcaWeb_FormatActiviteDetailJour
                - titre: "item.getLibelle()"
                  route: UcaWeb_FormatActiviteDetail
                  params: { idCa: idCa, idA: idA, id: id }
                  items:
                    - titre: "libelleRessource"
                      route: UcaWeb_FormatActiviteReservationDetailAnneeSemaine
                    - titre: "libelleRessource"
                      route: UcaWeb_FormatActiviteReservationDetailAnneeSemaineJour
                    - titre: "libelleRessource"
                      route: UcaWeb_FormatActiviteReservationDetail
    - titre: "trans('sitemap.installations.libelle')"
      route: UcaWeb_InstallationsSportives 

    - titre: "trans('sitemap.evenements.libelle')"
      route: UcaWeb_Evenement
      param: { page: '1' }
    - titre: "trans('sitemap.sporthautniveau.libelle')"
      route: UcaWeb_SportVoir

    - titre: "trans('sitemap.infospratiques.libelle')"
      route: UcaWeb_InfosPratiques
      
# Partie sans menu (ajout du paramètre : menu: 0)
    - titre: "trans('sitemap.connexion')"
      menu: 0
      route: fos_user_security_login
    - titre: "trans('sitemap.panier.libelle')"
      menu: 0
      route: UcaWeb_Panier
      droit: IS_AUTHENTICATED_FULLY
    - titre: "trans('sitemap.moncompte.libelle')"
      menu: 0
      route: UcaWeb_MonCompte
      droit: IS_AUTHENTICATED_FULLY
      items: 
        - titre: "trans('sitemap.moncompte.modifier.libelle')"
          menu: 0
          plansite: 0
          route: UcaWeb_MonCompte_Modifier
          droit: IS_AUTHENTICATED_FULLY
        - titre: "trans('sitemap.moncompte.changermotdepasse')"
          menu: 0
          plansite: 0
          route: fos_user_change_password
    - titre: "trans('sitemap.listeinscriptionavalider.libelle')"
      menu: 0
      route: UcaWeb_InscriptionAValiderLister
      droit: ROLE_ENCADRANT
      items:
        - titre: "trans('sitemap.inscriptionavalider.libelle')"
          menu: 0
          route: UcaWeb_InscriptionAValiderVoir
          params: { id: id }
    - titre: "trans('sitemap.mescommandes.libelle')"
      menu: 0
      route: UcaWeb_MesCommandes
      droit: IS_AUTHENTICATED_FULLY
      items:
        - titre: "trans('sitemap.detailscommande.libelle')"
          menu: 0
          route: UcaWeb_MesCommandesVoir
          droit: IS_AUTHENTICATED_FULLY
          params: { id: id }
          items:
            - titre: "trans('sitemap.recapitulatifcommande.libelle')"
              route: UcaWeb_PaiementRecapitulatif
              droit: IS_AUTHENTICATED_FULLY
              params: { id: id }
            - titre: "trans('sitemap.validationcommande.libelle')"
              route: UcaWeb_PaiementValidation
              droit: IS_AUTHENTICATED_FULLY
              params: { id: id }
            - titre: "trans('sitemap.validationcommande.libelle')"
              route: UcaWeb_PaiementRetourPaybox
              droit: IS_AUTHENTICATED_FULLY
              params: { id: id }
    - titre: "trans('sitemap.monplanning.libelle')"
      menu: 0
      droit: IS_AUTHENTICATED_FULLY
      route: UcaWeb_MonPlanning
      items:
        - titre: "trans('sitemap.monplanning.libelle')"
          menu: 0
          plansite: 0
          droit: IS_AUTHENTICATED_FULLY
          route: UcaWeb_PlanningMore
    - titre: "trans('sitemap.mesinscriptions.libelle')"
      menu: 0
      droit: IS_AUTHENTICATED_FULLY
      route: UcaWeb_MesInscriptions
      items:
        - titre: "trans('sitemap.detailinscription.libelle')"
          route: UcaWeb_MesInscriptionsVoir
          droit: IS_AUTHENTICATED_FULLY
          params: { id: id }
    - titre: "trans('sitemap.gestioncommande.libelle')"
      menu: 0
      route: UcaWeb_CommandeEnAttenteLister
      droit: ROLE_GESTION_PAIEMENT_COMMANDE
      items:
        - titre: "trans('sitemap.voir')"
          menu: 0
          route: UcaWeb_CommandeEnAttenteVoir
          params: { id: id }
    - titre: "trans('sitemap.preInscription.libelle')"
      menu: 0
      route: UcaWeb_preInscription
      items: 
        - titre: "trans('sitemap.preInscription_confirmation')"
          menu: 0
          plansite: 0
          route: UcaWeb_preInscription_confirmation

    - titre: "trans('footer.mentionslegales')"
      route: UcaWeb_MentionsLegales
      menu: 0
    - titre: "trans('footer.plandusite')"
      route: UcaWeb_PlanSite
      menu: 0
    - titre: "trans('footer.accessibilite')"
      route: UcaWeb_Accessibilite
      menu: 0
    - titre: "trans('footer.donneespersonnelles')"
      route: UcaWeb_DonneesPersonnelles
      menu: 0
    - titre: "trans('footer.cgv')"
      route: UcaWeb_CGV
      menu: 0
    - titre: "trans('footer.contact')"
      route: UcaWeb_Contact
      menu: 0
    - titre: "trans('sitemap.utilisateur.confirmation.invalide')"
      route: UtilisateurConfirmationInvalide
      menu: 0
      plansite: 0
    - titre: "trans('sitemap.utilisateur.confirmation')"
      route: fos_user_registration_confirmed
      menu: 0
      plansite: 0
    - titre: "trans('sitemap.utilisateur.changerMotdePasse')"
      route: fos_user_change_password
      menu: 0
      plansite: 0
    - titre: "trans('sitemap.utlisateur.reinitialiser')"
      route: fos_user_resetting_request
      menu: 0
      plansite: 0
      items:
        - titre: "trans('sitemap.utlisateur.reinitialiser.envoyer')"
          route: fos_user_resetting_send_email
          menu: 0
          plansite: 0
        - titre:  "trans('sitemap.utlisateur.reinitialiser.verification')"
          route: fos_user_resetting_check_email
          menu: 0
          plansite: 0
        - titre: "trans('sitemap.utlisateur.reinitialiser.reset')"
          route: fos_user_resetting_reset
          menu: 0
          plansite: 0

# Branche Uca Gest
- titre: "trans('sitemap.ucagest.libelle')"
  menuLevel: 2
  route: UcaGest_Accueil
  items:
    - titre: "trans('sitemap.activite.libelle')"
      route: null
      items:
        - titre: "trans('sitemap.typeactivite.libelle')"
          route: UcaGest_TypeActiviteLister
        
          droit: ROLE_GESTION_TYPE_ACTIVITE_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_TypeActiviteAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
              route: UcaGest_TypeActiviteModifier
  
        - titre: "trans('sitemap.classeactivite.libelle')"
          route: UcaGest_ClasseActiviteLister

          droit: ROLE_GESTION_CLASSE_ACTIVITE_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_ClasseActiviteAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
              route: UcaGest_ClasseActiviteModifier

        - titre: "trans('sitemap.activite.libelle')"
          route: UcaGest_ActiviteLister

          droit: ROLE_GESTION_ACTIVITE_LECTURE
          items:
            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
              route: UcaGest_ActiviteModifier

            - titre: "item.getActiviteLibelle()"
              route: UcaGest_ActiviteVoir

              params: { id: idActivite }
              items:
              - titre: "item.getLibelle()"
                route: UcaGest_FormatActiviteVoir

                params: { id: id }
              - titre: "trans('sitemap.format.ajouter')"
                route: UcaGest_FormatActiviteAjouter

                params: { id: id }
              - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
                route: UcaGest_FormatActiviteModifier

                params: { id: id }
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_ActiviteAjouter

              items:
                - titre: "item.getLibelle()"
                  route: UcaGest_FormatActiviteVoir

                  params: { id: id }

    - titre: "trans('sitemap.outils.libelle')"
      route: null

      items:
        - titre: "trans('sitemap.log.libelle')"
          route: UcaGest_LogLister

          droit: ROLE_GESTION_LOG_LECTURE
        - titre: "trans('sitemap.traduction.libelle')"
          route: UcaGest_TraductionLister

          droit: ROLE_GESTION_TRADUCTION_LECTURE
          items:
            - titre: "trans('sitemap.modifier')"
              route: UcaGest_TraductionModifier

    - titre: "trans('sitemap.referentiel.libelle')"
      route: null

      items:
        - titre: "trans('sitemap.profilutilisateur.libelle')"
          route: UcaGest_ProfilUtilisateurLister

          droit: ROLE_GESTION_PROFIL_UTILISATEUR_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_ProfilUtilisateurAjouter

            - titre: "trans('sitemap.modifier')"
              route: UcaGest_ProfilUtilisateurModifier

        - titre: "trans('sitemap.tarif.libelle')"
          route: UcaGest_TarifLister

          droit: ROLE_GESTION_TARIF_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_TarifAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
              route: UcaGest_TarifModifier

        - titre: "trans('sitemap.typeautorisation.libelle')"
          route: UcaGest_TypeAutorisationLister

          droit: ROLE_GESTION_TYPE_AUTORISATION_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_TypeAutorisationAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
              route: UcaGest_TypeAutorisationModifier

        - titre: "trans('sitemap.etablissement.libelle')"
          route: UcaGest_EtablissementLister

          droit: ROLE_GESTION_ETABLISSEMENT_LECTURE
          items:
            - titre: "item.getLibelle()"
              route: UcaGest_EtablissementVoir

            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_EtablissementAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
              route: UcaGest_EtablissementModifier

        - titre: "trans('sitemap.ressource.libelle')"
          route: UcaGest_RessourceLister

          droit: ROLE_GESTION_RESSOURCE_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_RessourceAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getLibelle()"
              route: UcaGest_RessourceModifier

            - titre: "item.getLibelle()"
              route: UcaGest_RessourceVoir

        - titre: "trans('sitemap.texte.libelle')"
          route: UcaGest_TexteLister

          droit: ROLE_GESTION_TEXTE_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: TexteAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getTitre()"
              route: UcaGest_TexteModifier

        - titre: "trans('sitemap.actualite.libelle')"
          route: UcaGest_ActualiteLister

          droit: ROLE_GESTION_TEXTE_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_ActualiteAjouter

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getTitre()"
              route: UcaGest_ActualiteModifier

        - titre: "trans('sitemap.imagefond.libelle')"
          route: UcaGest_ImageFondLister

          droit: ROLE_GESTION_IMAGEFOND_LECTURE
          items:
            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getTitre()"
              route: UcaGest_ImageFondModifier

    - titre: "trans('sitemap.securite.libelle')"
      route: null
      items:
        - titre: "trans('sitemap.utilisateur.libelle')"
          route: UcaGest_UtilisateurLister
          droit: ROLE_GESTION_UTILISATEUR_LECTURE
          items:
            - titre: "item.getPrenom() ~ ' ' ~ item.getNom()"
              route: UcaGest_UtilisateurVoir
              params: { id: id }
              items:
                - titre: "trans('sitemap.modifier')"
                  route: UcaGest_UtilisateurAjouterAutorisation

            - titre: "trans('sitemap.modifier') ~ ' ' ~ item.getPrenom() ~ ' ' ~ item.getNom()"
              route: UcaGest_UtilisateurModifier

            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_UtilisateurEnregistrement
              items:
                - titre: "trans('sitemap.utilisateur.verification')"
                  route: fos_user_registration_check_email

        - titre: "trans('sitemap.groupe.libelle')"
          route: UcaGest_GroupeLister
          droit: ROLE_GESTION_GROUPE_LECTURE
          items:
            - titre: "trans('sitemap.ajouter')"
              route: UcaGest_GroupeAjouter

            - titre: "trans('sitemap.modifier')"
              route: UcaGest_GroupeModifier

            - titre: "trans('sitemap.voir')"
              route: UcaGest_GroupeVoir

    - titre: "trans('sitemap.reportings.libelle')"
      route: null
      droit: ROLE_GESTION_COMMANDES
      items:
        - titre: "trans('sitemap.reportingcommandes.libelle')"
          route: UcaGest_ReportingCommandes
          items:
            - titre: "trans('sitemap.detailscommande.libelle')"
              route: UcaGest_ReportingCommandeDetails
              params: { id: id }
        - titre: "trans('sitemap.gestioninscription.libelle')"
          droit: ROLE_GESTION_INSCRIPTION
          route: UcaGest_GestionInscription
          items:
            - titre: "trans('sitemap.detailinscription.libelle')"
              route: UcaGest_GestionInscriptionVoir
              droit: ROLE_GESTION_INSCRIPTION
              params: { id: id }
    - titre: "trans('sitemap.parametrage.libelle')"
      route: null
      droit: ROLE_GESTION_PARAMETRAGE
      items:
        - titre: "trans('sitemap.parametrage.libelle')"
          route: UcaGest_Parametrage
          droit: ROLE_GESTION_PARAMETRAGE
          items:
            - titre: "trans('sitemap.modifier')"
              route: UcaGest_ParametrageModifier
              droit: ROLE_GESTION_PARAMETRAGE

          

